default:
    image: python:3.7.3
    before_script:
        - pip install poetry
        - touch .env
        - touch pyproject.toml # force make setup to run

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - dist

stages:
    - test
    - release

test-package:
    stage: test
    script:
        - make test

publish-package:
    stage: release
    rules:
        - if: '$CI_COMMIT_TAG != null'
    variables:
        FINDPAPERS_PYPI_API_TOKEN: $FINDPAPERS_PYPI_API_TOKEN
    script:
        - make publish
